version: '3'

services:
  php_backup_sastra:
    build: .
    container_name: php_backup_sastra
    image: latest
    volumes:
      - ./src:/var/www/html
      - ./httpd.vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 46:80