version: '3'

services:
  php_sastra:
    build: ./php
    image: php_sastra:latest
    container_name: php_sastra
    hostname: php
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/html
    depends_on:
      - db_sastra

  db_sastra:
    image: mariadb:10.2
    container_name: db_sastra
    restart: always
    tty: true
    ports:
      - "62307:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false

  nginx_sastra:
    build: ./nginx
    image: nginx_sastra:latest
    container_name: nginx_sastra
    hostname: nginx
    restart: always
    ports:
      - "52:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_sastra
